### ISSUE TITLE
Maps stopped working after update

### ISSUE THREAD

**Issue by donce** [divio/djangocms-googlemap#15]
After this update https://github.com/divio/djangocms-googlemap/pull/5 I started receiving this error, which prevents showing maps:
`Uncaught TypeError: Cannot read property 'appendChild' of null`
This exception is thrown in downloaded google js file (https://maps-api-ssl.google.com/...) on line:
`document.body.appendChild(s);`
because document.body is still `null`.
I am testing with a single map on a page.

**Comment by FinalAngel** [comment]
Please reopen if this is still relevant with the latest release
