### ISSUE TITLE
form GoogleMapForm needs updating (RemovedInDjango18Warning)

### ISSUE THREAD

**Issue by saeedsq** [divio/djangocms-googlemap#20]
C:\Python27\lib\site-packages\djangocms_googlemap\forms.py:14: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form GoogleMapForm needs updating
  class GoogleMapForm(ModelForm):

**Comment by saeedsq** [comment]
I see that you have fixed the issue in your development version, When do plan to release next version.
Just waiting to here from you

**Comment by bittner** [comment]
@czpython This issue can be closed as soon as there is a new release on PyPI. Any plans on when v0.5.2 will be packaged and uploaded?
