### ISSUE TITLE
Styled maps

### ISSUE THREAD

**Issue by asermax** [divio/djangocms-googlemap#3]
Any plans on allowing maps [custom sytling](https://developers.google.com/maps/documentation/javascript/styling?csw=1)?

**Comment by bittner** [comment]
That would make sense. Would be awesome! :+1:

**Comment by bittner** [comment]
This is already possible via the "CUSTOM MAP STYLE" text area at the bottom of the "Change google map" dialog. The input box expects valid JSON as described in the [Google Maps API docs](https://developers.google.com/maps/documentation/javascript/styling).

##  Valid JSON For Styling (Example)

Note that the sample code Google gives in their [Google Maps API docs](https://developers.google.com/maps/documentation/javascript/styling) is not [valid JSON](http://jsonlint.com/). If you want to try out that styling the corresponding valid JSON you can paste into the CMS plugin's text box is:
``` JSON
[{
	"featureType": "all",
	"stylers": [{
		"saturation": "-80"
	}]
}, {
	"featureType": "road.arterial",
	"elementType": "geometry",
	"stylers": [{
		"hue": "#00ffee"
	}, {
		"saturation": "50"
	}]
}, {
	"featureType": "poi.business",
	"elementType": "labels",
	"stylers": [{
		"visibility": "off"
	}]
}]
```

According to my understanding this issue can be closed.
