### ISSUE TITLE
Google Maps is now requiring an api key

### ISSUE THREAD

**Issue by roemhildtg** [divio/djangocms-googlemap#36]
Maps on new website will not load without an api key, but there isn't a way to configure an api key afaik. 

I get this error in the browser console.

"Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"

Related: https://www.drupal.org/node/2758179

**Comment by bittner** [comment]
I fixed this issue, on another fork though.

[djangocms-maps](https://pypi.python.org/pypi/djangocms-maps) supports several map providers and has Google Maps API key support.

Looks like pretty much all map providers now ask for API keys. No service otherwise.  :confused:

**Comment by FinalAngel** [comment]
Fixed by https://github.com/divio/djangocms-googlemap/pull/46
