### ISSUE TITLE
djangocms-googlemap should not assume that jQuery is available on page.

### ISSUE THREAD

**Issue by macolo** [divio/djangocms-googlemap#37]
If I include the plugin on a page without jQuery I get the following error:

```
djangocms.googlemaps.js:29 Uncaught ReferenceError: $ is not defined

```

Shouldnt the plugin load the system jQuery if there is no frontend-side jQuery available (or: always)?

**Comment by FinalAngel** [comment]
@macolo throwing a console error is correct. Addons should never load the django system jQuery but depend on your frontend. If you wish so, you can adapt the template then. Though we'll include a warning into the javascript to make it more clear.

**Comment by macolo** [comment]
@FinalAngel thanks for clarification, that makes sense. Actually, as I am using system.js I was able to patch the template accordingly - that is quite an advantage.

**Comment by FinalAngel** [comment]
👍

**Comment by FinalAngel** [comment]
updated version now includes vanilla javascript: https://github.com/divio/djangocms-googlemap/pull/46
