### ISSUE TITLE
Missing migration for 0.5.1

### ISSUE THREAD

**Issue by bittner** [divio/djangocms-googlemap#39]
Similar to https://github.com/divio/djangocms-inherit/issues/26 with django CMS 3.3.2 on Django 1.8.14 there is a migration missing for this CMS plugin.

## See Also

https://github.com/divio/django-cms/issues/5550 is probably the issue related to migrations of this and other CMS plugins.

**Comment by czpython** [comment]
Thanks.
Fixed by 464045b430e7bc3db6f4e7005091e57aef801bda
Unrelated to https://github.com/divio/django-cms/issues/5550
