### ISSUE TITLE
Django CMS requirements

### ISSUE THREAD

**Issue by petrklus** [divio/djangocms-googlemap#50]
Hi,

I have been using Django CMS 3.2 on the Aldryn platform and the  djangocms-googlemap is pulled automatically. 

Latest update breaks my deployment as it forces minimal Django CMS version to 3.3, and I am running on 3.2.

**Comment by FinalAngel** [comment]
this has been fixed on Divio Cloud: https://github.com/aldryn/aldryn-django-cms/pull/82
