### ISSUE TITLE
Conflicting migrations detected; multiple leaf nodes in the migration graph

### ISSUE THREAD

**Issue by FabrizioA** [divio/djangocms-googlemap#52]
Hi,

I'm trying to upgrade djangocms-googlemaps from v. 0.5.1 to the last one. When I launch python manage.py migrate I get the error:

`CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0008_removed_null_fields, 0003_auto_20161115_0927 in djangocms_googlemap).
To fix them run 'python manage.py makemigrations --merge'`

Here my showmigrations:

djangocms_googlemap
 [X] 0001_initial
 [X] 0002_auto_20160622_1031
 [X] 0003_auto_20161115_0927
 [ ] 0003_auto_20160825_1829
 [ ] 0004_adapted_fields
 [ ] 0005_create_nested_plugins
 [ ] 0006_remove_fields
 [ ] 0007_reset_null_values
 [ ] 0008_removed_null_fields

the double 0003 migration is strange...

Any suggestion?

Thank you
Fabrizio

**Comment by FinalAngel** [comment]
@FabrizioA there are no double 3 migrations available: https://github.com/divio/djangocms-googlemap/tree/master/djangocms_googlemap/migrations I'd suggest checking your virtualenv on what was installed.

**Comment by FabrizioA** [comment]
Re-HI Angelo :)

I have remove the extra 003 migration and go works ok!

Thank you
F.
