### ISSUE TITLE
lat/lng incorrect for locales not using point as decimal separator

### ISSUE THREAD

**Issue by kese** [divio/djangocms-googlemap#53]
Hello,

the values of lat/lng data-attributes should be forcibly output unlocalized in the according templates, since not all locales (e.g. german) use a period as decimal separator. (and values get incorrectly parsed as integers if a comma is used.)

fortunately this can be simply achieved by appling a stringformat filter like this.

`data-lat="{{ instance.lat|stringformat:"f" }}"`

**Comment by FinalAngel** [comment]
@kese thanks for the report, would you be able to open a PR to address this issue?
