### ISSUE TITLE
zoom level needs to be asynchronously set

### ISSUE THREAD

**Issue by kese** [divio/djangocms-googlemap#54]
Hello,

as discussed [here](http://stackoverflow.com/questions/4523023/using-setzoom-after-using-fitbounds-with-google-maps-api-v3) the maps zoom level should be asynchronously set (on first `bounds_changed` event) after calling `fitBounds` on the map.

**Comment by FinalAngel** [comment]
@kese thanks for the report, would you be able to open a PR to address this issue?
