### ISSUE TITLE
aldryn_config.py: API key should be in an Environment variable

### ISSUE THREAD

**Issue by stefanfoulis** [divio/djangocms-googlemap#64]
Having it in the config form commits it to code and makes it harder to have a different API key for test/live/local or other environments.

**Comment by FinalAngel** [comment]
@stefanfoulis is this something you can add to the config?

**Comment by czpython** [comment]
Fixed by https://github.com/divio/djangocms-googlemap/commit/838e4d8fa765addad9765279570d5a5779c9a3f4
