### ISSUE TITLE
Django Compressor

### ISSUE THREAD

**Issue by alexemorris** [divio/djangocms-googlemap#67]
This plugin is great but its automatically adding incompressible files to my js block which is causing a server error when compression is enabled. Is there an easy way to override this?

**Comment by FinalAngel** [comment]
You could compress the JS file yourself: https://github.com/divio/djangocms-googlemap/blob/master/djangocms_googlemap/static/djangocms_googlemap/js/djangocms.googlemap.js

Or override the template to use your own google map implementation: 
https://github.com/divio/djangocms-googlemap/blob/master/djangocms_googlemap/templates/djangocms_googlemap/default/map.html#L28
