### ISSUE TITLE
[Question] Does this have a search plugin

### ISSUE THREAD

**Issue by mykljohn** [divio/djangocms-googlemap#68]
Hi, great integration, but I was wondering 2 things actually.   

1.  Does this have a search plugin similar to Aldryn-Locations?  

2.  Can I pre-load my map with out store locations like https://developers.google.com/maps/solutions/store-locator/clothing-store-locator?

cheers, Mykl

**Comment by FinalAngel** [comment]
@mykljohn the search capabilities from aldryn-locations can be build into this addon, this is merely frontend and you would need to adapt the HTML / CSS code.

The backend functionality is all there.
