### ISSUE TITLE
[Question] Limit Markers via select and redraw map

### ISSUE THREAD

**Issue by mykljohn** [divio/djangocms-googlemap#69]
Hi, I've used DjangoCMS Forms to add 2 fields and a button as in the image.  

![image](https://user-images.githubusercontent.com/11919990/28381674-5125a94a-6c81-11e7-93a4-d0aae51a5cde.png)

My idea is to programmatically populate the Marker table via the model when a new Item and Location is added. (Storing the slug in the Marker InfoWindow Content.) 

Here's my model:  
```
class Items(models.Model):
    user = models.ForeignKey(User, related_name='proprietor', blank=True, null=True)
    title = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    descripcion = models.TextField(blank=True, null=True)
    imagen = models.ImageField(upload_to='media')
    location = PlacesField(blank=True, )

``` 
So when the user presses Buscar, I want to select GoogleMapMarker where info_content like "%"+ <search value> +"%" and then redraw the map limited to those results.

Can you point me in the right direction to accomplish this?

**Comment by FinalAngel** [comment]
@mykljohn to clarify some implementation points, do you already draw all possible locations onto the map? If so you'd somewhere in JS need to store the relevant data in the marker element and then filter the map according to the selection. This would all be done using JS.

If you have to redraw the data from the backend then it might be more complex. You would have to load the matching markers via AJAX and then update the map.

**Comment by mykljohn** [comment]
Hey, thanks for the reply.  My original idea was to resubmit the query, but I think you right it might be faster to do it in JS.  I could load the data in the info window when then map is initially drawn and then I guess could search for all markers that are like the input.  Not sure how to go about that :(

**Comment by FinalAngel** [comment]
@mykljohn thats how I would do it. Though that also depends on the data size. If its a couple of hundred pins - then there is no problem. Otherwise it can get more complicated.
