### ISSUE TITLE
Publish to PyPi version 1.3.0

### ISSUE THREAD

**Issue by DmytroLitvinov** [divio/djangocms-googlemap#85]
Hello @vThaian @FinalAngel .

I see you have added support for new version of python, django and djangocms.
Will you release changes to PyPi?

**Comment by FinalAngel** [comment]
@DmytroLitvinov yes, we're awaiting for QA to approve the changes. We'll most likely release by mid-week

**Comment by DmytroLitvinov** [comment]
@FinalAngel any change to [merge it](https://github.com/divio/djangocms-googlemap/pull/86) also into new version?

**Comment by FinalAngel** [comment]
We'll need to test it first @DmytroLitvinov, I'll try to squeeze it in but no promises. If you add tests that would help 👍

**Comment by DmytroLitvinov** [comment]
@FinalAngel done!
https://github.com/divio/djangocms-googlemap/pull/86
You could check it here.

**Comment by FinalAngel** [comment]
@DmytroLitvinov awesome, we're currently testing on Divio Cloud :)

**Comment by DmytroLitvinov** [comment]
Nice to hear it. I hope with my PR? :)

**Comment by FinalAngel** [comment]
yep :)

**Comment by FinalAngel** [comment]
Releasing now
